package com.mycompany.apps.mapper;

import com.mycompany.apps.entity.Grouptable;
import org.apache.ibatis.annotations.Param;

public interface GrouptableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TUTORIAL.GROUPTABLE
     *
     * @mbggenerated Mon Jan 20 21:48:37 JST 2014
     */
    int deleteByPrimaryKey(@Param("username") String username, @Param("groupid") String groupid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TUTORIAL.GROUPTABLE
     *
     * @mbggenerated Mon Jan 20 21:48:37 JST 2014
     */
    int insert(Grouptable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TUTORIAL.GROUPTABLE
     *
     * @mbggenerated Mon Jan 20 21:48:37 JST 2014
     */
    int insertSelective(Grouptable record);
}