package com.mycompany.apps.mapper;

import com.mycompany.apps.entity.Usertable;

public interface UsertableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TUTORIAL.USERTABLE
     *
     * @mbggenerated Mon Jan 20 21:48:37 JST 2014
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TUTORIAL.USERTABLE
     *
     * @mbggenerated Mon Jan 20 21:48:37 JST 2014
     */
    int insert(Usertable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TUTORIAL.USERTABLE
     *
     * @mbggenerated Mon Jan 20 21:48:37 JST 2014
     */
    int insertSelective(Usertable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TUTORIAL.USERTABLE
     *
     * @mbggenerated Mon Jan 20 21:48:37 JST 2014
     */
    Usertable selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TUTORIAL.USERTABLE
     *
     * @mbggenerated Mon Jan 20 21:48:37 JST 2014
     */
    int updateByPrimaryKeySelective(Usertable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TUTORIAL.USERTABLE
     *
     * @mbggenerated Mon Jan 20 21:48:37 JST 2014
     */
    int updateByPrimaryKey(Usertable record);
}